name: Run Notebooks & Publish Reports

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with: python-version: 3.8
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Data & preprocess
        run: |
          make data
          make preprocess
      - name: Execute notebooks
        run: make notebooks
      - name: Upload reports
        uses: actions/upload-artifact@v3
        with:
          name: notebook-outputs
          path: executed/*.html
